"""Initial migration

Revision ID: 586a5f1e12ef
Revises: 
Create Date: 2024-02-05 06:10:29.648652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586a5f1e12ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_reviews')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poster_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True)
        # Provide a name for the foreign key constraint
        batch_op.create_foreign_key('fk_movies_category', 'all_categories', ['category_id'], ['id'])
        batch_op.drop_column('release_date')
        batch_op.drop_column('overview')
        batch_op.drop_column('tmdb_id')
        batch_op.drop_column('popularity')
        batch_op.drop_column('language')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('popularity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('overview', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), nullable=True))
        # Refer to the foreign key constraint by its name to drop it
        batch_op.drop_constraint('fk_movies_category', type_='foreignkey')
        batch_op.alter_column('title',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('poster_url')
        batch_op.drop_column('description')
        batch_op.drop_column('year')

    op.create_table('movie_reviews',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('movie_id', sa.INTEGER(), nullable=False),
                    sa.Column('review', sa.VARCHAR(length=500), nullable=False),
                    sa.Column('rating', sa.INTEGER(), nullable=True),
                    sa.Column('likes', sa.INTEGER(), nullable=True),
                    sa.Column('dislikes', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
